name: Enforce Tag Protection

on:
  push:
    tags:
      - 'v1*'
      - 'v2*'
      - 'v3*'

jobs:
  enforce-tag-protection:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Enforce tag protection
        run: |
          echo "Enforcing protection policies for tags matching v1* and v2*"
          # GitHub CLI command to update protection settings
          gh api -X PUT \
            -H "Accept: application/vnd.github.v3+json" \
            /repos/${{ github.repository }}/branches/${{ github.ref_name }}/protection \
            -F required_pull_request_reviews.dismiss_stale_reviews=true \
            -F required_pull_request_reviews.required=true
