name: Create Pull Request on New Tag

on:
  push:
    tags:
      - 'v1*'
      - 'v2*'
      - 'v3*'

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up GitHub CLI
        uses: cli/gh-action@v2

      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Creating pull request for new tag ${{ github.ref_name }}"
          BRANCH_NAME="release-${{ github.ref_name }}"
          # Create a new branch
          git checkout -b $BRANCH_NAME
          git push origin $BRANCH_NAME
          # Create a pull request
          PULL_REQUEST_URL=$(gh pr create --title "Release ${{ github.ref_name }}" --body "This PR is for the new tag ${{ github.ref_name }}" --head $BRANCH_NAME --base main --json url -q ".url")
          echo "Pull Request created: $PULL_REQUEST_URL"

      - name: Request Reviewer Approval
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Requesting reviewer approval for the pull request"
          gh pr review --request @danie182004 $PULL_REQUEST_URL
