name: Enforce Tag Protection

on:
  push:
    tags:
      - 'v1*'
      - 'v2*'

jobs:
  validate-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Check tag format
        run: |
          echo "Validating tag format..."
          if [[ ! $GITHUB_REF =~ ^refs/tags/v[12][0-9]* ]]; then
            echo "Invalid tag format. Allowed: v1*, v2*"
            exit 1
          fi
          echo "Tag format is valid: $GITHUB_REF"

  require-approval:
    needs: validate-tag
    runs-on: ubuntu-latest
    permissions:
      actions: write

    steps:
      - name: Await manual approval
        uses: harmon758/wait-for-approval-action@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          timeout: 60m # Set timeout for review (e.g., 1 hour)
